part of 'theme.dart';

// Ignore redundant arguments as this is a generated file template pattern.
// ignore_for_file: avoid_redundant_argument_values

/// Generated by Forui CLI.
///
/// Style tokens and theme extensions for the generated theme.
FStyle _style({
  required FColors colors,
  required FTypography typography,
  required bool touch,
}) {
  const borderRadius = FBorderRadius();
  return FStyle(
    formFieldStyle: .inherit(
      colors: colors,
      typography: typography,
      touch: touch,
    ),
    focusedOutlineStyle: FFocusedOutlineStyle(
      color: colors.primary,
      borderRadius: borderRadius.md,
    ),
    sizes: FSizes.inherit(touch: touch),
    iconStyle: IconThemeData(
      color: colors.foreground,
      size: typography.body.lg.fontSize,
    ),
    tappableStyle: FTappableStyle(),
    borderRadius: const FBorderRadius(),
    borderWidth: 1,
    pagePadding: const .symmetric(vertical: 8, horizontal: 12),
    shadow: const [
      BoxShadow(color: Color(0x0d000000), offset: Offset(0, 1), blurRadius: 2),
    ],
    extensions: const [AppStyle()],
  );
}

/// Provides convenient access to theme extensions on [FStyle].
///
/// ```dart
/// final cardRadius = context.theme.style.app.cardRadius; ✅
///
/// // Alternatively, you can create a getter to access extension fields directly.
/// final cardRadius = context.theme.style.cardRadius; ✅
///
/// final cardRadius = context.theme.style.extension<AppStyle>().cardRadius; ❌
/// ```
extension FStyleExtensions on FStyle {
  AppStyle get app => extension<AppStyle>();
}

/// Custom style tokens unique to your app.
///
/// Add your fields below, then implement [copyWith], [lerp], [==], and [hashCode].
/// See https://api.flutter.dev/flutter/material/ThemeExtension-class.html.
@immutable
class AppStyle extends ThemeExtension<AppStyle> {
  const AppStyle({
    this.iconBgOpacity = 0.12,
    this.iconBorderOpacity = 0.20,
  });

  final double iconBgOpacity;
  final double iconBorderOpacity;

  // Design system constants mapped to forui scale
  double get xs => 8;
  double get sm => 12;
  double get md => 16;
  double get lg => 20;
  double get xl => 24;
  double get xxl => 32;
  double get xl3 => 40;
  double get xl4 => 48;

  /// Gold-standard vertical gap between major sections/blocks on a screen.
  ///
  /// Matches the Home screen baseline (`lg`, 20px) and is the single source of
  /// truth for section-to-section spacing across every scrollable screen.
  double get section => lg;

  /// Gold-standard vertical gap between a section header and its content.
  double get sectionContent => md;

  @override
  AppStyle copyWith({
    double? iconBgOpacity,
    double? iconBorderOpacity,
  }) {
    return AppStyle(
      iconBgOpacity: iconBgOpacity ?? this.iconBgOpacity,
      iconBorderOpacity: iconBorderOpacity ?? this.iconBorderOpacity,
    );
  }

  @override
  AppStyle lerp(covariant AppStyle? other, double t) {
    if (other == null) {
      return this;
    }
    return AppStyle(
      iconBgOpacity: lerpDouble(iconBgOpacity, other.iconBgOpacity, t) ?? iconBgOpacity,
      iconBorderOpacity: lerpDouble(iconBorderOpacity, other.iconBorderOpacity, t) ?? iconBorderOpacity,
    );
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AppStyle &&
          runtimeType == other.runtimeType &&
          iconBgOpacity == other.iconBgOpacity &&
          iconBorderOpacity == other.iconBorderOpacity;

  @override
  int get hashCode => Object.hash(runtimeType, iconBgOpacity, iconBorderOpacity);
}
