part of 'theme.dart';

// Ignore redundant arguments as this is a generated file template pattern.
// ignore_for_file: avoid_redundant_argument_values

/// The Poka border-radius scale.
///
/// Overrides the ForUI defaults with a slightly rounder, more even progression. Radii that keep their
/// ForUI default (`xs2` 4, `xs` 6, `pill` 100) are intentionally omitted.
///
/// | Token | Value | Applies to                                                  |
/// |-------|-------|-------------------------------------------------------------|
/// | `sm`  | 10    | Chips, badges, status pills, icon tiles                     |
/// | `md`  | 12    | Buttons, text fields, selects, tabs, keypad keys            |
/// | `lg`  | 16    | Cards — transaction rows, balance widget, summary report    |
/// | `xl`  | 20    | Hero surfaces, dialogs                                      |
/// | `xl2` | 24    | Bottom sheets (top corners)                                 |
/// | `xl3` | 28    | Full-height modal headers                                   |
const FBorderRadius _borderRadius = FBorderRadius(
  sm: BorderRadius.all(Radius.circular(10)),
  md: BorderRadius.all(Radius.circular(12)),
  lg: BorderRadius.all(Radius.circular(16)),
  xl: BorderRadius.all(Radius.circular(20)),
  xl2: BorderRadius.all(Radius.circular(24)),
  xl3: BorderRadius.all(Radius.circular(28)),
);

/// Generated by Forui CLI.
///
/// Style tokens and theme extensions for the generated theme.
FStyle _style({required FColors colors, required FTypography typography, required bool touch}) {
  return FStyle(
    formFieldStyle: .inherit(colors: colors, typography: typography, touch: touch),
    focusedOutlineStyle: FFocusedOutlineStyle(color: colors.primary, borderRadius: _borderRadius.md),
    sizes: FSizes.inherit(touch: touch),
    iconStyle: IconThemeData(color: colors.foreground, size: typography.body.lg.fontSize),
    tappableStyle: FTappableStyle(),
    borderRadius: _borderRadius,
    borderWidth: 1,
    pagePadding: const .symmetric(vertical: 8, horizontal: 12),
    shadow: const [BoxShadow(color: Color(0x0d000000), offset: Offset(0, 1), blurRadius: 2)],
    extensions: const [AppStyle()],
  );
}

/// Provides convenient access to theme extensions on [FStyle].
///
/// ```dart
/// final cardRadius = context.theme.style.app.radiusCard; ✅
///
/// // Alternatively, you can create a getter to access extension fields directly.
/// final cardRadius = context.theme.style.radiusCard; ✅
///
/// final cardRadius = context.theme.style.extension<AppStyle>().radiusCard; ❌
/// ```
extension FStyleExtensions on FStyle {
  AppStyle get app => extension<AppStyle>();
}

/// Ready-made flat decorations for Poka's surface ladder.
///
/// Poka expresses elevation with a **surface step plus a border** — never a shadow. These helpers keep
/// that contract in one place so a transaction card, a balance widget and a summary report cannot drift
/// apart. The shape matches ForUI's own `FCard` (rounded superellipse), so hand-built containers sit
/// flush next to ForUI components.
///
/// ```dart
/// DecoratedBox(decoration: context.theme.cardDecoration, child: ...);
/// ```
extension PokaDecorations on FThemeData {
  /// Level 1 — standard card: transaction row, balance widget, summary report block.
  ShapeDecoration get cardDecoration =>
      _surface(colors.app.surfaces.raised, colors.app.surfaces.border, _borderRadius.lg);

  /// Level 1 emphasised — selected or focused card.
  ShapeDecoration get selectedCardDecoration =>
      _surface(colors.app.surfaces.raised, colors.app.surfaces.borderStrong, _borderRadius.lg);

  /// Level 0 — recessed well: grouped-list backdrop, chart plot area, empty state.
  ShapeDecoration get sunkenDecoration =>
      _surface(colors.app.surfaces.sunken, colors.app.surfaces.borderSubtle, _borderRadius.lg);

  /// Level 2 — modal plane: dialogs and popovers.
  ShapeDecoration get overlayDecoration =>
      _surface(colors.app.surfaces.overlay, colors.app.surfaces.borderStrong, _borderRadius.xl);

  /// Level 2 — bottom sheet, rounded on the top edge only.
  BoxDecoration get sheetDecoration => BoxDecoration(
    color: colors.app.surfaces.overlay,
    border: Border(
      top: BorderSide(color: colors.app.surfaces.borderStrong, width: style.borderWidth),
    ),
    borderRadius: const .vertical(top: .circular(24)),
  );

  /// Filled form control — text field, select, keypad key.
  ShapeDecoration get fieldDecoration =>
      _surface(colors.app.surfaces.input, colors.app.surfaces.border, _borderRadius.md);

  /// Tinted chip for a semantic value, e.g. `theme.chipDecoration(theme.colors.app.finance.incomeSoft)`.
  ShapeDecoration chipDecoration(Color tint) => ShapeDecoration(
    shape: const RoundedSuperellipseBorder(borderRadius: .all(.circular(10))),
    color: tint,
  );

  ShapeDecoration _surface(Color fill, Color border, BorderRadius radius) => ShapeDecoration(
    shape: RoundedSuperellipseBorder(
      side: BorderSide(color: border, width: style.borderWidth),
      borderRadius: radius,
    ),
    color: fill,
  );
}

/// Custom style tokens unique to your app.
///
/// Add your fields below, then implement [copyWith], [lerp], [==], and [hashCode].
/// See https://api.flutter.dev/flutter/material/ThemeExtension-class.html.
@immutable
class AppStyle extends ThemeExtension<AppStyle> {
  const new({this.iconBgOpacity = 0.12, this.iconBorderOpacity = 0.20});

  final double iconBgOpacity;
  final double iconBorderOpacity;

  // Design system constants mapped to forui scale
  double get xs => 8;
  double get sm => 12;
  double get md => 16;
  double get lg => 20;
  double get xl => 24;
  double get xxl => 32;
  double get xl3 => 40;
  double get xl4 => 48;

  /// Gold-standard vertical gap between major sections/blocks on a screen.
  ///
  /// Matches the Home screen baseline (`lg`, 20px) and is the single source of
  /// truth for section-to-section spacing across every scrollable screen.
  double get section => lg;

  /// Gold-standard vertical gap between a section header and its content.
  double get sectionContent => md;

  // ── Radius scale ──────────────────────────────────────────────────────────
  // Named aliases over [_borderRadius] so widgets express intent ("this is a card")
  // rather than a size ("this is lg").

  /// 10px — chips, badges, status pills, icon tiles.
  BorderRadius get radiusChip => _borderRadius.sm;

  /// 12px — buttons, text fields, selects, tabs, keypad keys.
  BorderRadius get radiusControl => _borderRadius.md;

  /// 16px — transaction cards, balance widget, summary report blocks.
  BorderRadius get radiusCard => _borderRadius.lg;

  /// 20px — hero surfaces such as the gradient balance card.
  BorderRadius get radiusHero => _borderRadius.xl;

  /// 20px — dialogs.
  BorderRadius get radiusDialog => _borderRadius.xl;

  /// 24px, top corners only — bottom sheets.
  BorderRadius get radiusSheet => const .vertical(top: .circular(24));

  /// Fully rounded — avatars, toggle thumbs, segmented controls.
  BorderRadius get radiusFull => _borderRadius.pill;

  @override
  AppStyle copyWith({double? iconBgOpacity, double? iconBorderOpacity}) {
    return AppStyle(
      iconBgOpacity: iconBgOpacity ?? this.iconBgOpacity,
      iconBorderOpacity: iconBorderOpacity ?? this.iconBorderOpacity,
    );
  }

  @override
  AppStyle lerp(covariant AppStyle? other, double t) {
    if (other == null) {
      return this;
    }
    return AppStyle(
      iconBgOpacity: lerpDouble(iconBgOpacity, other.iconBgOpacity, t) ?? iconBgOpacity,
      iconBorderOpacity: lerpDouble(iconBorderOpacity, other.iconBorderOpacity, t) ?? iconBorderOpacity,
    );
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AppStyle &&
          runtimeType == other.runtimeType &&
          iconBgOpacity == other.iconBgOpacity &&
          iconBorderOpacity == other.iconBorderOpacity;

  @override
  int get hashCode => Object.hash(runtimeType, iconBgOpacity, iconBorderOpacity);
}
