import 'package:forui/forui.dart';
import 'package:material_ui/material_ui.dart';

// ForUI CLI generated code.
// ignore_for_file: unnecessary_ignore
// ignore_for_file: avoid_redundant_argument_values

/// Generated by Forui CLI.
///
/// Modify the generated function bodies to create your own custom style.
/// Then, call the modified functions and pass the results to your FThemeData.
///
/// ### Example
/// Generated style:
/// ```dart
/// // Modify this function's body.
/// FDividerStyles dividerStyles({
///   required FColorScheme color,
///   required FStyle style,
/// }) => FDividerStyles(
///   horizontalStyle: FDividerStyle(
///     colors: colors.secondary,
///     padding: FDividerStyle.defaultPadding.horizontalStyle,
///     width: style.borderWidth,
///   ),
///   verticalStyle: FDividerStyle(
///     colors: colors.secondary,
///     padding: FDividerStyle.defaultPadding.verticalStyle,
///     width: style.borderWidth,
///   ),
/// );
/// ```
///
/// File that contains your `FThemeData`:
/// ```dart
/// import 'package:my_application/theme/divider_style.dart' // Your generated style file.
///
/// FThemeData(
///  color: FTheme.neutral.light.touch.color,
///  style: FTheme.neutral.light.touch.style,
///  dividerStyles: CustomFDividerStyles.dividerStyles( // The function in your generated style file.
///    color: FTheme.neutral.light.touch.color,
///    style: FTheme.neutral.light.touch.style,
///   ),
/// );
/// ```
///
/// A theme can be generated using the Forui CLI:
/// ```shell
/// dart forui theme create [theme name]
/// ```
///
/// See https://forui.dev/docs/guides/customizing-themes for more information.
FTabsStyle tabsStyle({required FColors colors, required FTypography typography, required FStyle style}) => FTabsStyle(
  decoration: ShapeDecoration(
    shape: RoundedSuperellipseBorder(
      side: BorderSide(color: colors.border, width: style.borderWidth),
      borderRadius: style.borderRadius.md,
    ),
    color: Colors.transparent,
  ),
  labelTextStyle: FVariants.from(
    typography.body.sm.copyWith(fontWeight: .w500, color: colors.mutedForeground),
    variants: {
      [.selected]: .delta(color: colors.primary),
    },
  ),
  indicatorDecoration: ShapeDecoration(
    shape: RoundedSuperellipseBorder(
      side: BorderSide(color: colors.primary.withValues(alpha: 0.5), width: style.borderWidth),
      borderRadius: style.borderRadius.md,
    ),
    color: colors.primary.withValues(alpha: 0.04),
  ),
  focusedOutlineStyle: style.focusedOutlineStyle,
  padding: const .all(4),
  indicatorSize: .tab,
  minHeight: 36,
  spacing: 10,
);
